import carData from '@/data/default_car_data.json';
import suvData from '@/data/default_suv_data.json';
import truckData from '@/data/default_truck_data.json';
import CarPlaceholder from '@/images/suggested/CarPlaceholder.webp';
import SUVPlaceholder from '@/public/custom-cover/sc-01-ps-gr-1to-m.webp';
import TruckPlaceholder from '@/public/custom-cover/tc-01-ps-gr-1to-m.webp';
import defaultCarPremiumPlus from '@/images/default-product-images/01-bkrd-str-m.jpg';
import defaultSUVPremiumPlus from '@/public/pms/suv-01-bkgr-str-m.webp';
import defaultTruckPremiumPlus from '@/public/pms/tc-01-bkgr-str-m.webp';

export const US_STATES = [
  { name: 'Alabama', abbreviation: 'AL' },
  { name: 'Alaska', abbreviation: 'AK' },
  { name: 'Arizona', abbreviation: 'AZ' },
  { name: 'Arkansas', abbreviation: 'AR' },
  { name: 'California', abbreviation: 'CA' },
  { name: 'Colorado', abbreviation: 'CO' },
  { name: 'Connecticut', abbreviation: 'CT' },
  { name: 'Delaware', abbreviation: 'DE' },
  { name: 'Florida', abbreviation: 'FL' },
  { name: 'Georgia', abbreviation: 'GA' },
  { name: 'Hawaii', abbreviation: 'HI' },
  { name: 'Idaho', abbreviation: 'ID' },
  { name: 'Illinois', abbreviation: 'IL' },
  { name: 'Indiana', abbreviation: 'IN' },
  { name: 'Iowa', abbreviation: 'IA' },
  { name: 'Kansas', abbreviation: 'KS' },
  { name: 'Kentucky', abbreviation: 'KY' },
  { name: 'Louisiana', abbreviation: 'LA' },
  { name: 'Maine', abbreviation: 'ME' },
  { name: 'Maryland', abbreviation: 'MD' },
  { name: 'Massachusetts', abbreviation: 'MA' },
  { name: 'Michigan', abbreviation: 'MI' },
  { name: 'Minnesota', abbreviation: 'MN' },
  { name: 'Mississippi', abbreviation: 'MS' },
  { name: 'Missouri', abbreviation: 'MO' },
  { name: 'Montana', abbreviation: 'MT' },
  { name: 'Nebraska', abbreviation: 'NE' },
  { name: 'Nevada', abbreviation: 'NV' },
  { name: 'New Hampshire', abbreviation: 'NH' },
  { name: 'New Jersey', abbreviation: 'NJ' },
  { name: 'New Mexico', abbreviation: 'NM' },
  { name: 'New York', abbreviation: 'NY' },
  { name: 'North Carolina', abbreviation: 'NC' },
  { name: 'North Dakota', abbreviation: 'ND' },
  { name: 'Ohio', abbreviation: 'OH' },
  { name: 'Oklahoma', abbreviation: 'OK' },
  { name: 'Oregon', abbreviation: 'OR' },
  { name: 'Pennsylvania', abbreviation: 'PA' },
  { name: 'Rhode Island', abbreviation: 'RI' },
  { name: 'South Carolina', abbreviation: 'SC' },
  { name: 'South Dakota', abbreviation: 'SD' },
  { name: 'Tennessee', abbreviation: 'TN' },
  { name: 'Texas', abbreviation: 'TX' },
  { name: 'Utah', abbreviation: 'UT' },
  { name: 'Vermont', abbreviation: 'VT' },
  { name: 'Virginia', abbreviation: 'VA' },
  { name: 'Washington', abbreviation: 'WA' },
  { name: 'West Virginia', abbreviation: 'WV' },
  { name: 'Wisconsin', abbreviation: 'WI' },
  { name: 'Wyoming', abbreviation: 'WY' },
  { name: 'Guam', abbreviation: 'GU' },
  { name: 'US Virgin Islands', abbreviation: 'VI' },
  { name: 'Puerto Rico', abbreviation: 'PR' },
] as const;

export const SHIPPING_RATES = [
  {
    shipping_type: 'Free Shipping',
    shipping_cost: 0,
    shipping_method: 'FedEx Ground',
    product_types: ['Car Covers', 'SUV Covers', 'Truck Covers'],
    states_excluded: ['AK', 'HI', 'PR', 'VI', 'GU'],
  },
  {
    shipping_type: 'Paid Shipping',
    shipping_cost: 25,
    shipping_method: 'FedEx 2-Day Guaranteed Delivery',
    product_types: ['Car Covers', 'SUV Covers'],
    states_excluded: ['GU', 'VI', 'PR'],
  },
  {
    shipping_type: 'Paid Shipping',
    shipping_cost: 50,
    shipping_method: 'FedEx 2-Day Guaranteed Delivery',
    product_types: ['Car Covers', 'SUV Covers'],
    states_excluded: ['AK', 'HI'],
  },
  {
    shipping_type: 'Paid Shipping',
    shipping_cost: 65,
    shipping_method: 'FedEx 2-Day Guaranteed Delivery',
    product_types: ['Truck Cover'],
    states_excluded: [],
  },
] as const;

export const slugToProductType = {
  'car-covers': 'Car Covers',
  'suv-covers': 'SUV Covers',
  'truck-covers': 'Truck Covers',
};

export const slugToCoverType = {
  'premium-plus': 'Premium Plus',
  premium: 'Premium',
  'standard-pro': 'Standard Pro',
  standard: 'Standard',
};

export const PRODUCT_PRICING_DATA = {
  'car-covers': [
    {
      msrp: '159.95',
      price: '320.00',
      description: 'Fully Custom Car Cover',
      image: defaultCarPremiumPlus,
      type: {
        slug: 'premium-plus',
        display: 'Premium Plus',
      },
    },
    {
      msrp: '119.95',
      price: '240.00',
      description: 'Semi-Custom Car Cover',
      image: CarPlaceholder,
      type: {
        slug: 'premium',
        display: 'Premium',
      },
    },

    {
      msrp: '100.00',
      price: '100.00',
      description: 'Semi-Custom Car Cover',
      image: CarPlaceholder,
      type: {
        slug: 'standard-pro',
        display: 'Standard Pro',
      },
    },
    {
      msrp: '80.00',
      price: '80.00',
      description: 'Semi-Custom Car Cover',
      image: CarPlaceholder,
      type: {
        slug: 'standard',
        display: 'Standard',
      },
    },
  ],
  'suv-covers': [
    {
      msrp: '179.95',
      price: '360.00',
      description: 'Fully Custom SUV Cover',
      image: defaultSUVPremiumPlus,
      type: {
        slug: 'premium-plus',
        display: 'Premium Plus',
      },
    },
    {
      msrp: '139.95',
      price: '280.00',
      description: 'Semi-Custom SUV Cover',
      image: SUVPlaceholder,
      type: {
        slug: 'premium',
        display: 'Premium',
      },
    },

    {
      msrp: '120.00',
      price: '120.00',
      description: 'Semi-Custom SUV Cover',
      image: SUVPlaceholder,
      type: {
        slug: 'standard-pro',
        display: 'Standard Pro',
      },
    },

    {
      msrp: '100.00',
      price: '100.00',
      description: 'Semi-Custom SUV Cover',
      image: SUVPlaceholder,
      type: {
        slug: 'standard',
        display: 'Standard',
      },
    },
  ],
  'truck-covers': [
    {
      msrp: '199.95',
      price: '400.00',
      description: 'Fully Custom Truck Cover',
      image: defaultTruckPremiumPlus,
      type: {
        slug: 'premium-plus',
        display: 'Premium Plus',
      },
    },
    {
      msrp: '159.95',
      price: '320.00',
      description: 'Semi-Custom Truck Cover',
      image: defaultTruckPremiumPlus,
      type: {
        slug: 'premium',
        display: 'Premium',
      },
    },

    {
      msrp: '140.00',
      price: '140.00',
      description: 'Semi-Custom Truck Cover',
      image: TruckPlaceholder,
      type: {
        slug: 'standard-pro',
        display: 'Standard Pro',
      },
    },
    {
      msrp: '120.00',
      price: '120.00',
      description: 'Semi-Custom Truck Cover',
      image: TruckPlaceholder,
      type: {
        slug: 'standard',
        display: 'Standard',
      },
    },
  ],
};

export type TProductPricingConstant = typeof PRODUCT_PRICING_DATA;

export const colorOrder = [
  'Black Red Stripe',
  'Black Gray Stripe',
  'Gray Black Stripe',
  'Black Gray 2-Tone',
  'Black Red 2-Tone',
  'Gray Black Tribe',
  'Solid Gray',
] as const;

export const typeOrder = [
  'Premium Plus',
  'Premium',
  'Standard Pro',
  'Standard',
];

export const skuTypes = [
  'SKU_pe_bkgr_str',
  'SKU_pe_bkrd_str',
  'SKU_pp_bkgr_str',
  'SKU_pp_bkrd_str',
  'SKU_pp_grbk_str',
  'SKU_pp_bkgr_2to',
  'SKU_pp_bkrd_2to',
  'SKU_pp_grbk_tri',
  'SKU_ps_gr_1to',
  'SKU_sp_gr_1to',
  'SKU_ss_gr_1to',
];

export const VIMEO_VIDEO_LINK = 'https://vimeo.com/904161479';

const suvImages: Partial<Record<(typeof colorOrder)[number], string[]>> = {
  'Black Gray Stripe': [
    'http://www.coverland.com/category-images-new/suv-premium-plus-bkgr-str.webp',
    'http://www.coverland.com/category-images-new/02-SC-ft-ps-bkgr-str.webp',
    'http://www.coverland.com/category-images-new/04-oxford-outer-black.webp',
    'http://www.coverland.com/category-images-new/05-oxford-inner.webp',
    'http://www.coverland.com/category-images-new/09-value.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Solid Gray': [
    'http://www.coverland.com/category-images-new/suv-standard-pro-gr-1to.webp',
    'http://www.coverland.com/category-images-new/02-SC-ft-sp-gr-1to.webp',
    'http://www.coverland.com/category-images-new/05-SC-ps-gr-1to.webp',
    'http://www.coverland.com/category-images-new/06-sp-gr-1to.webp',
    'http://www.coverland.com/category-images-new/07-sp-gr-1to.webp',
    'http://www.coverland.com/category-images-new/12.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
};
const carImages: Partial<Record<(typeof colorOrder)[number], string[]>> = {
  'Black Red Stripe': [
    'https://www.coverland.com/images/default-product-images/01-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/02-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/03-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/04-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/05-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/06-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/07-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/08-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/09-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/10-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/11-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/12-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/13-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/14-bkrd-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],

  'Black Gray Stripe': [
    'https://www.coverland.com/images/default-product-images/01-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/02-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/03-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/04-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/05-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/06-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/07-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/08-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/09-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/10-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/11-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/12-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/13-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/14-bkgr-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Gray Black Stripe': [
    'https://www.coverland.com/images/default-product-images/01-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/02-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/03-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/04-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/05-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/06-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/07-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/08-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/09-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/10-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/11-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/12-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/13-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/14-grbk-str-m.jpg',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Black Gray 2-Tone': [
    'http://www.coverland.com/pms/01-2to-bkgr.webp',
    'http://www.coverland.com/pms/02-bkgr-2to-mr.webp',
    'http://www.coverland.com/pms/03-2to-bkgr.webp',
    'http://www.coverland.com/pms/04-oxford-outer-black.webp',
    'http://www.coverland.com/pms/05-oxford-inner.webp',
    'http://www.coverland.com/pms/06-bkgr-2to.webp',
    'http://www.coverland.com/pms/07-uv-protection.webp',
    'http://www.coverland.com/pms/08-simulation.webp',
    'http://www.coverland.com/pms/09-value.webp',
    'http://www.coverland.com/pms/10-2to-bkgr.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Black Red 2-Tone': [
    'http://www.coverland.com/pms/01-2to-bkrd.webp',
    'http://www.coverland.com/pms/02-bkrd-2to-mr.webp',
    'http://www.coverland.com/pms/03-2to-bkrd.webp',
    'http://www.coverland.com/pms/04-oxford-outer-black.webp',
    'http://www.coverland.com/pms/05-oxford-inner.webp',
    'http://www.coverland.com/pms/06-bkrd-2to.webp',
    'http://www.coverland.com/pms/07-uv-protection.webp',
    'http://www.coverland.com/pms/08-simulation.webp',
    'http://www.coverland.com/pms/09-value.webp',
    'http://www.coverland.com/pms/10-2to-bkrd.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Gray Black Tribe': [
    'http://www.coverland.com/pms/01-tri-grbk.webp',
    'http://www.coverland.com/pms/02-grbk-tri-mr.webp',
    'http://www.coverland.com/pms/03-tri-grbk.webp',
    'http://www.coverland.com/pms/04-oxford-outer-black.webp',
    'http://www.coverland.com/pms/05-oxford-inner.webp',
    'http://www.coverland.com/pms/06-grbk-tri.webp',
    'http://www.coverland.com/pms/07-uv-protection.webp',
    'http://www.coverland.com/pms/08-simulation.webp',
    'http://www.coverland.com/pms/09-value.webp',
    'http://www.coverland.com/pms/10-tri-grbk.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Solid Gray': [
    'http://www.coverland.com/pms/01-ps-gr-1to.webp',
    'http://www.coverland.com/pms/02-sol-gr-mr.webp',
    'http://www.coverland.com/pms/03-sol-gr.webp',
    'http://www.coverland.com/pms/04-oxford-outer-black.webp',
    'http://www.coverland.com/pms/05-oxford-inner.webp',
    'http://www.coverland.com/pms/06-sol-gr.webp',
    'http://www.coverland.com/pms/07-uv-protection.webp',
    'http://www.coverland.com/pms/08-simulation.webp',
    'http://www.coverland.com/pms/09-value.webp',
    'http://www.coverland.com/pms/10-sol-gr.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
};

const truckImages: Partial<Record<(typeof colorOrder)[number], string[]>> = {
  'Black Gray Stripe': [
    'http://www.coverland.com/category-images-new/01-str-bkgr-truck.webp',
    'http://www.coverland.com/category-images-new/02-str-bkgr-truck.webp',
    'http://www.coverland.com/category-images-new/04-oxford-outer-black.webp',
    'http://www.coverland.com/category-images-new/05-oxford-inner.webp',
    'http://www.coverland.com/category-images-new/09-value.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
  'Solid Gray': [
    'http://www.coverland.com/category-images-new/truck-premium-gr-1to.webp',
    'http://www.coverland.com/category-images-new/02-tc-ft-sp-gr-1to.webp',
    'http://www.coverland.com/category-images-new/06-ps-gr-1to.webp',
    'http://www.coverland.com/category-images-new/07-ps-gr-1to.webp.webp',
    'http://www.coverland.com/category-images-new/12.webp',
    'https://www.coverland.com/images/default-product-images/15.jpg',
  ],
};

export const DEFAULT_PRODUCT_IMAGES = { suvImages, carImages, truckImages };

export const defaultCarModelData = carData;
export const defaultSuvModelData = suvData;
export const defaultTruckModelData = truckData;

export const TEST_ORDER_NUMBER = 'CL-TEST-ORDER-2024';

export const CAR_COVER_MAKES = [
  'Ford',
  'Maserati',
  'Dodge',
  'Infiniti',
  'Bentley',
  'Peugeot',
  'Pontiac',
  'Plymouth',
  'Audi',
  'MG',
  'Lexus',
  'Jeep',
  'Volvo',
  'Acura',
  'Cadillac',
  'Suzuki',
  'International',
  'Laforza',
  'Aston Martin',
  'Mitsubishi',
  'AM General',
  'Chrysler',
  'Isuzu',
  'GMC',
  'Lincoln',
  'Honda',
  'Scion',
  'Chevrolet',
  'Saturn',
  'Porsche',
  'Alfa Romeo',
  'Mercedes',
  'Lada',
  'Rolls-Royce',
  'Tesla',
  'Jaguar',
  'Renault',
  'Kia',
  'Lamborghini',
  'Oldsmobile',
  'Fiat',
  'Land Rover',
  'Opel',
  'Rivian',
  'Buick',
  'Nissan',
  'Genesis',
  'Saab',
  'Hyundai',
  'Geo',
  'Subaru',
  'Mazda',
  'BMW',
  'Volkswagen',
  'Seat',
  'Mercury',
  'Hummer',
  'Toyota',
];
export const SUV_COVER_MAKES = [
  'DeSoto',
  'Ford',
  'Maserati',
  'Dodge',
  'Willys',
  'Infiniti',
  'MINI',
  'Fisker',
  'Bentley',
  'Jensen',
  'Excalibur',
  'Pontiac',
  'Plymouth',
  'Frazer',
  'Audi',
  'MG',
  'Lexus',
  'Hudson',
  'Volvo',
  'AMC',
  'Lancia',
  'Cadillac',
  'Acura',
  'Polestar',
  'Suzuki',
  'Mitsubishi',
  'Aston Martin',
  'Amphicar',
  'DeTomaso',
  'Nash Hudson',
  'Bricklin',
  'Ferrari',
  'Chrysler',
  'Packard',
  'Lincoln',
  'Simca',
  'Honda',
  'Scion',
  'Daimler',
  'Shelby',
  'Studebaker',
  'Chevrolet',
  'Kaiser',
  'Saturn',
  'Avanti',
  'AC',
  'Triumph',
  'Hillman',
  'Edsel',
  'Karma',
  'Porsche',
  'Lucid',
  'DeLorean',
  'Alfa Romeo',
  'Mercedes',
  'Rolls-Royce',
  'Tesla',
  'Rover',
  'Jaguar',
  'Renault',
  'Lotus',
  'Kia',
  'Oldsmobile',
  'Fiat',
  'Opel',
  'Buick',
  'Nash',
  'Nissan',
  'Iso',
  'Genesis',
  'Hyundai',
  'Saab',
  'Citroen',
  'Geo',
  'Merkur',
  'Coachsmiths',
  'Subaru',
  'Mazda',
  'BMW',
  'Volkswagen',
  'Mercury',
  'Eagle',
  'Toyota',
  'Austin-Healey',
  'Datsun',
];

export const TRUCK_COVER_MAKES = [
  'Ford',
  'Dodge',
  'RAM',
  'GWM',
  'Holden',
  'LDV',
  'GMC',
  'Honda',
  'Chevrolet',
  'Rivian',
  'Nissan',
  'Hyundai',
  'Toyota',
];

export const BASE_URL =
  process.env.NODE_ENV === 'production'
    ? 'http://localhost:3000'
    : 'http://localhost:3000';
